[package]
name = "orig-protocol-http"
version.workspace = true
edition.workspace = true

[dependencies]
orig-core = { path = "../orig-core" }
orig-net = { path = "../orig-net" }
async-trait.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
reqwest.workspace = true
futures.workspace = true
