[package]
name = "orig-net"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
if-addrs = "0.13"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.59", features = [
    "Win32_Foundation",
    "Win32_NetworkManagement_IpHelper",
    "Win32_Networking_WinSock",
    "Win32_System_Memory",
] }
network-interface = "2.0.5"

[target.'cfg(target_os = "linux")'.dependencies]
rtnetlink = "0.22"
futures = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
